#!/bin/sh

name=binutils
version=2.45.1
allow_network=yes

tarball_url="https://mirrors.ocf.berkeley.edu/gnu/binutils/binutils-${version}.tar.xz"
tarball_sha256="5fe101e6fe9d18fdec95962d81ed670fdee5f37e3f48f0bef87bddf862513aa5"
