#!/bin/sh

name=gcc
version=15.2.0
allow_network=yes

tarball_url="https://mirrors.ocf.berkeley.edu/gnu/gcc/gcc-${version}/gcc-${version}.tar.xz"
tarball_sha256="438fd996826b0c82485a29da03a72d71d6e3541a83ec702df4271f6fe025d24e"
