#!/bin/sh

JINX_MAJOR_VER=0.8
JINX_ARCH=x86_64
JINX_DEBIAN_SNAPSHOT="20260320T113529Z"

JINX_BASE_PACKAGES="build-essential clang llvm-19 llvm-19-tools lld nasm meson ninja-build libgmp-dev libmpfr-dev libmpc-dev wget mtools autoconf automake"

TARGET_CFLAGS="-O2"
TARGET_CXXFLAGS="-O2"
TARGET_LDFLAGS=""
TARGET_TRIPLET="x86_64-evalynos"

HOST_CFLAGS="-O2"
HOST_CXXFLAGS="-O2"
HOST_LDFLAGS=""

KERNEL_CFLAGS="-flto -DMUTE_KERNEL_PANIC"
