#!/bin/sh

git submodule update --init --recursive

set -e

mkdir -p ./iso/EFI/BOOT
cp /usr/share/limine/BOOTX64.EFI ./iso/EFI/BOOT/
cp /usr/share/limine/limine-bios-cd.bin ./iso/bios.bin
cp /usr/share/limine/limine-uefi-cd.bin ./iso/uefi.bin

cp /usr/share/edk2/x64/OVMF_CODE.4m.fd .
cp /usr/share/edk2/x64/OVMF_VARS.4m.fd .

printf "Dependencies obtained successfully.\n\n"
