#!/bin/sh

name=gcc
from_source=gcc
revision=0
hostdeps="binutils"
deps="mlibc-headers"

configure() {
    CFLAGS="$HOST_CFLAGS" \
    CXXFLAGS="$HOST_CXXFLAGS" \
    LDFLAGS="$HOST_LDFLAGS" \
    "${source_dir}"/configure \
        --target=x86_64-evalynos \
        --prefix="${prefix}" \
        --with-sysroot="${sysroot_dir}" \
        --enable-languages=c,c++ \
        --enable-threads=posix \
        --disable-multilib \
        --disable-shared \
        --disable-host-shared
}

build() {
    make all-gcc all-target-libgcc -j${parallelism}
}

package() {
    make DESTDIR="${dest_dir}" install-gcc install-target-libgcc
}
