#! /bin/sh

name=limine
from_source=limine
revision=0

allow_network=yes

build() {
    cp -rpf "${source_dir}"/. ./
    ./bootstrap
    CC_FOR_TARGET=gcc LD_FOR_TARGET=ld OBJCOPY_FOR_TARGET=objcopy OBJDUMP_FOR_TARGET=objdump READELF_FOR_TARGET=readelf CFLAGS_FOR_TARGET="-O2 -pipe"\
    ./configure  --enable-bios-cd --enable-bios-pxe --enable-bios --enable-uefi-ia32 --enable-uefi-x86-64 --enable-uefi-cd --prefix="${prefix}"
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}
