#!/bin/sh

name=ovmf2-bin
from_source=ovmf2-bin
revision=0

build() {
    cp -rpf "${source_dir}"/. ./
}

package() {
    cp ./ovmf-code-x86_64.fd ${dest_dir}
    cp ./ovmf-vars-x86_64.fd ${dest_dir}
}
